# Your AWS Account ID
accountId: ''
# Choose region closest to for optimal latency
# https://aws.amazon.com/about-aws/global-infrastructure/regions_az/
region: eu-north-1
# EC2
amiName: steamcmd-ubuntu-server-v1.0.0
# input the name of the EC2 key pair you generated
keyPairName: steamcmd-eu-north-1
# Whitelist your public IP address to access SSH
# https://www.google.com/search?q=what+is+my+ip
# Replace 127.0.0.1 with your own public IP
sshIpAddressWhitelist:
  - 127.0.0.1

servers:
  - serverName: reforger-server-01 # serverName must match the directory name in the servers/ directory
    game: reforger
    rootVolumeSizeGB: 15 # Temporary disk terminated on every time instance is stopped
    dataVolumeSizeGB: 30 # Permanent disk for game install files
    instanceClass: m7a
    instanceSize: medium
    # Optional: automatic shutdown schedule, example schedule shuts down the server daily at 3am UTC time
    # Documentation https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events.CronOptions.html
    shutDownSchedule:
      minute: '0'
      hour: '3'
    # Optional: automatic start up schedule, example schedule start the server daily at 4pm UTC time
    # Only specify if you wish to start your server automatically
    #startUpSchedule:
    #  minute: '0'
    #  hour: '16'
    firewallOpenings:
      - description: Game port
        protocol: udp
        portNumber: 2001
      - description: RCON
        protocol: udp
        portNumber: 19999
      - description: Steam A2S
        protocol: udp
        portNumber: 17777